In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

In [22]:
from sklearn.datasets import make_regression

In [23]:
X,y = make_regression(n_samples=100,n_features=2,n_informative=2,n_targets=1,noise=10) 

In [24]:
df = pd.DataFrame({'f1':X[:,0],'f2':X[:,1],'t':y})

In [25]:
df.shape

(100, 3)

In [26]:
df.head()

f1        f2          t
0  0.092502 -0.323400 -23.490496
1  0.172935  0.404796  34.125069
2 -0.133476 -1.073122 -66.187039
3  0.453364  0.054238  14.292004
4 -0.867003  0.520712  18.235969

In [27]:
fig = px.scatter_3d(df,x='f1',y='f2',z='t')
fig.show()

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=3)

In [29]:
from sklearn.linear_model import LinearRegression

In [30]:
lr = LinearRegression()

In [31]:
lr.fit(X_train,y_train)

LinearRegression()

In [32]:
y_pred = lr.predict(X_test)

In [33]:
y_pred

array([ -95.82614972,  -77.6061373 ,  -35.4249496 ,   80.18591809,
        -34.74439805,   -4.08901374,   40.91366618,  112.81248598,
         90.34944684, -144.58297481,   16.41588405,  -15.12832888,
        150.98684286,   93.78495388,  -58.38058656,  -34.00940604,
         48.87741846, -130.41661717,   73.62474797,   81.16984937])

In [34]:
y_test

array([ -93.02267722,  -79.13183182,  -39.54750401,   83.61936606,
        -36.26156458,  -17.82679579,   19.08958463,  115.89258091,
        103.46694676, -154.4547355 ,    5.86762619,  -18.48975411,
        148.86754107,  102.16249656,  -63.77032484,  -23.87553093,
         53.09139445, -141.36863993,   82.23875793,   95.49039656])

In [35]:
X_train.shape

(80, 2)

In [36]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
print('MAE',mean_absolute_error(y_test,y_pred))
print('MSE',mean_squared_error(y_test,y_pred))
print('RMSE',np.sqrt(mean_squared_error(y_test,y_pred)))
print('R2_score',r2_score(y_test,y_pred))
r2 = r2_score(y_test,y_pred)
adj_r2 = 1 - (((1-r2)*(20-1))/(40-1-1))
print('R2_score_adjusted',adj_r2)

MAE 7.653212596883828
MSE 86.56327897666358
RMSE 9.303938895793737
R2_score 0.988361204177643
R2_score_adjusted 0.9941806020888215


In [38]:
lr.coef_
## beta-1 and beta-2

array([18.28018697, 55.33926598])

In [40]:
lr.intercept_
## beta-0

2.189948918404444